### ISSUE TITLE
Problema con pedidos cancelados

### ISSUE THREAD

**Issue by arsonists** [aplazame/prestashop#30]
Buenas tardes,

Tengo la versión 3.0.3 y me he dado cuenta que el módulo crea el pedido/orden aunque este sea cancelado por parte de Aplazame y lo pone automáticamente en el estado "Cancelado". 

Considero que solo debería de crearlo cuando Aplazame acepte la financiación/pago, porque sino.. se nos puede llenar el backoffice de pedidos cancelados.

En otra tienda tengo la versión v1.0.11 y sin problemas.

**Comment by Maks3w** [comment]
Hola @arsonists 

  El comportamiento que describes es el que realiza PrestaShop para cualquier método de pago que requiere de un trámite externo. También es el comportamiento habitual en cualquier otro modelo de tienda cuando hace falta reservar el inventario (billete de avión, butaca de cine) durante un tiempo.

  En definitiva, no es algo que realicemos nosotros a voluntad.

Saludos.

**Comment by arsonists** [comment]
Hola de nuevo,

Discrepo con su respuesta. 
Por ejemplo, con el módulo PayPal, TPVs, etc si en el pedido el pago no es aceptado, sale un mensaje de error y no se crea el pedido, cuando el pago es aceptado, se crea el pedido. Imagino que el correspondiente módulo da la orden a Prestashop de pago aceptado.

Esto es una cosa básica y de sentido común.

Como también le he dicho, en otra tienda utilizó la versión v1.0.11 y esta no me crea pedidos cuando es cancelado por Aplazame, por lo que alguna respuesta habrá a que una versión lo haga y otra no.

Un saludo.

**Comment by Maks3w** [comment]
Buenos días @arsonists 

  ¿Podrías escribirnos a soporte@aplazame.com indicando el listado de órdenes de compra?

Gracias.

**Comment by arsonists** [comment]
hecho. :)
