### ISSUE TITLE
Division by zero modules/aplazame/lib/Aplazame/Aplazame/BusinessModel/Order.php

### ISSUE THREAD

**Issue by didacrios** [aplazame/prestashop#55]
> Division by zero in modules/aplazame/lib/Aplazame/Aplazame/BusinessModel/Order.php on line 31

Buenas, no he podido reproducir el caso exacto, pero si que he visto muchos logs con este error, por si quisierais considerar hacer algun tipo de check para asegurarse que el proceso se cumple o salte algun tipo de error por algun tipo de inconsistencia

Saludos

**Comment by alexhernandezord** [comment]
Issue fixed on last releases.
